[package]
name = "duo-snake"
version = "0.1.0"
edition = "2024"

[lib]
name = "duo_snake"
crate-type = ["rlib", "cdylib"]
path = "src/lib.rs"

[[bin]]
name = "DuoSnake"
path = "src/main.rs"

[dependencies]
bevy = "0.14.0"
rand = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom_v2 = { package = "getrandom", version = "0.2", features = ["js"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
uuid = { version = "1", features = ["js"] }
wasm-bindgen = "0.2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
